# Generated by Django 5.0.6 on 2024-08-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('site_name', 'Site Name'), ('logo_image', 'Logo Image'), ('instagram_link', 'Instagram Link')], max_length=255, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
