# Generated by Django 5.0.6 on 2024-08-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srixz', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_cover/')),
                ('about_me', models.TextField()),
                ('my_mission', models.TextField()),
            ],
        ),
    ]
