# Generated by Django 5.0.6 on 2024-08-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srixz', '0006_about_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('price', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
    ]
