# Generated by Django 5.0.6 on 2024-08-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srixz', '0008_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
