# Generated by Django 5.0.6 on 2024-08-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srixz', '0009_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
