# Generated by Django 4.2.2 on 2024-08-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srixz', '0010_alter_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='service_cover/'),
            preserve_default=False,
        ),
    ]
