# Generated by Django 4.2.2 on 2024-08-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srixz', '0012_alter_gallery_category_alter_gallery_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='show_in_gallery',
            field=models.BooleanField(default=True),
        ),
    ]
