# Generated by Django 4.2.2 on 2024-08-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srixz', '0013_gallery_show_in_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
            ],
        ),
    ]
