# Generated by Django 4.2.2 on 2024-08-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srixz', '0014_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
