# Generated by Django 4.2.2 on 2024-09-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srixz', '0015_enquiry_email_enquiry_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='bannerimage/')),
            ],
        ),
    ]
