# Generated by Django 4.2.2 on 2024-09-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srixz', '0017_remove_gallery_image_remove_gallery_show_in_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
