# Generated by Django 4.2.2 on 2024-09-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srixz', '0018_alter_gallery_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='key',
            field=models.CharField(choices=[('site_name', 'Site Name'), ('logo_image', 'Logo Image'), ('instagram_link', 'Instagram Link'), ('pintrest_link', 'pintrest_link'), ('facebook_link', 'facebook_link'), ('youtube_link', 'youtube_link')], max_length=255, unique=True),
        ),
    ]
