# Generated by Django 4.2.2 on 2024-09-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srixz', '0019_alter_sitesetting_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='key',
            field=models.CharField(choices=[('site_name', 'Site Name'), ('logo_image', 'Logo Image'), ('instagram_link', 'Instagram Link'), ('pintrest_link', 'Pintrest link'), ('facebook_link', 'Facebook link'), ('youtube_link', 'Youtube link')], max_length=255, unique=True),
        ),
    ]
